// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart';
import 'package:ser_manos/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    final secret = await SecretLoader(secretPath: "assets/secrets.json").load();

    if (kIsWeb) {
      return webFirebaseOptions(secret.webApiKey);
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidFirebaseOptions(secret.androidApiKey);
      case TargetPlatform.iOS:
        return iosFirebaseOptions(secret.iosApiKey);
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static FirebaseOptions webFirebaseOptions(String apiKey) {
    return FirebaseOptions(
      apiKey: apiKey,
      appId: '1:58443286682:web:29e8ca7eac3ff8541bf723',
      messagingSenderId: '58443286682',
      projectId: 'ser-manos-62724',
      authDomain: 'ser-manos-62724.firebaseapp.com',
      storageBucket: 'ser-manos-62724.appspot.com',
      measurementId: 'G-8Y48PP29PN',
    );
  }

  static FirebaseOptions iosFirebaseOptions(String apiKey) {
    return FirebaseOptions(
      apiKey: apiKey,
      appId: '1:58443286682:android:fda313c80d081bfa1bf723',
      messagingSenderId: '58443286682',
      projectId: 'ser-manos-62724',
      storageBucket: 'ser-manos-62724.appspot.com',
    );
  }

  static FirebaseOptions androidFirebaseOptions(String apiKey) {
    return FirebaseOptions(
      apiKey: apiKey,
      appId: '1:58443286682:ios:c155329cc27572ec1bf723',
      messagingSenderId: '58443286682',
      projectId: 'ser-manos-62724',
      authDomain: 'ser-manos-62724.firebaseapp.com',
      storageBucket: 'ser-manos-62724.appspot.com',
      measurementId: 'G-8Y48PP29PN',
    );
  }
}
